version: "3"
services:
  redis:
    container_name: redisss
    restart: always
    image: redis
    build:
      context: ./redis
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network
    ports:
      - 6399:6399

  thechats:
    container_name: thechats
    restart: always
    image: thechats
    build:
      context: ./node
    volumes:
      - ./node/:/usr/src/app
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_HOST=${NEW_RELIC_HOST}
    depends_on:
      - redis
    networks:
      - network
    ports:
      - 5000:5000

networks:
  network:

volumes:
  db: